[build]
  command = "yarn build && yarn postexport"
  publish = "out"


[dev]
  targetPort = 8000

[[plugins]]
  package = "netlify-plugin-chromium"

[[redirects]]
  from = "/events/2023/09/manchester-code-sitecore-usergroup"
  to = "/events/2023-09-manchester-code-sitecore-usergroup"
  status = 301
  force = false

[[redirects]]
  from = "/events/2024-01-manchester-unrvld-sitecore-usergroup"
  to = "/events/2024-03-manchester-unrvld-sitecore-usergroup"
  status = 301
  force = false